import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import zlib from 'node:zlib';
import {createRequire} from 'node:module';
import {fileURLToPath,pathToFileURL} from 'node:url';

const require=createRequire(import.meta.url);
const ROOT=path.dirname(fileURLToPath(import.meta.url));
const HOST='127.0.0.1',PORT=Number(process.env.REV_BROWSER_HOST_PORT||43119);
const WORKER=String(process.env.REV_WORKER_URL||'https://kyron-gateway.kyron012345678910.workers.dev').replace(/\/$/,'');
const PROFILE=process.env.REV_BROWSER_PROFILE||'D:\\kyron-state\\BrowserHost\\ChatGPTProfile';
const CHROME=process.env.REV_CHROME_PATH||'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe';
let browser=null,puppeteer=null;

function loadPuppeteer(){if(puppeteer)return puppeteer;try{puppeteer=require('puppeteer-core')}catch{puppeteer=require('D:/kyron-state/Tools/DesktopCommander/Runtime/node_modules/puppeteer-core')}return puppeteer}
function allowedDomain(d){d=String(d||'').replace(/^\./,'').toLowerCase();return d==='chatgpt.com'||d.endsWith('.chatgpt.com')||d==='openai.com'||d.endsWith('.openai.com')}
function sameSite(v){v=String(v||'').toLowerCase();return v==='strict'?'Strict':v==='lax'?'Lax':v==='no_restriction'||v==='none'?'None':undefined}
function cookieParam(c){if(!c||typeof c!=='object'||!c.name||typeof c.value!=='string'||!allowedDomain(c.domain))return null;const domain=String(c.domain||'').replace(/^\./,''),secure=c.secure!==false,pathName=c.path||'/',out={name:String(c.name),value:c.value,path:pathName,secure,httpOnly:!!c.httpOnly};if(c.hostOnly||String(c.name).startsWith('__Host-'))out.url=`${secure?'https':'http'}://${domain}${pathName}`;else out.domain=String(c.domain||domain);const ss=sameSite(c.sameSite);if(ss)out.sameSite=ss;const exp=Number(c.expirationDate);if(Number.isFinite(exp)&&exp>0)out.expires=exp;return out}

export function parseSitevault(input){const b=Buffer.isBuffer(input)?input:Buffer.from(input),magic=b.subarray(0,11).toString('utf8');if(magic!=='SITEVAULT3\n'&&magic!=='SITEVAULT2\n')throw new Error('Unsupported SiteVault format.');if(b.length<15)throw new Error('SiteVault is truncated.');const n=b.readUInt32LE(11);if(n<2||n>1024*1024||15+n>b.length)throw new Error('SiteVault header is invalid.');let h;try{h=JSON.parse(b.subarray(15,15+n).toString('utf8'))}catch{throw new Error('SiteVault header is invalid.')}if(h?.encrypted)throw new Error('Encrypted SiteVault is not supported by browser host.');let payload=b.subarray(15+n);if(h?.codec==='gzip')payload=zlib.gunzipSync(payload);let v;try{v=JSON.parse(payload.toString('utf8'))}catch{throw new Error('SiteVault payload is invalid.')}const origin=String(v?.source?.origin||h?.source?.origin||'');if(origin!=='https://chatgpt.com')throw new Error('SiteVault is not a direct ChatGPT session.');const cookies=(Array.isArray(v?.cookies)?v.cookies:[]).map(cookieParam).filter(Boolean);if(!cookies.length)throw new Error('SiteVault contains no usable ChatGPT cookies.');return{header:h,data:v,cookies}}

async function ensureBrowser(){if(browser?.connected)return browser;fs.mkdirSync(PROFILE,{recursive:true});const p=loadPuppeteer();browser=await p.launch({executablePath:CHROME,headless:false,userDataDir:PROFILE,defaultViewport:null,args:['--no-first-run','--disable-sync','--disable-default-apps','--disable-features=Translate']});browser.on('disconnected',()=>{browser=null});return browser}
async function applySession(buf){const v=parseSitevault(buf),b=await ensureBrowser(),pages=await b.pages(),page=pages[0]||await b.newPage(),cdp=await page.createCDPSession();await cdp.send('Network.enable');await cdp.send('Network.clearBrowserCookies');let ok=0,failed=0;for(const c of v.cookies){try{const r=await cdp.send('Network.setCookie',c);r?.success===false?failed++:ok++}catch{failed++}}if(!ok)throw new Error('No ChatGPT cookies could be restored.');await page.goto('https://chatgpt.com/',{waitUntil:'domcontentloaded',timeout:30000}).catch(()=>{});await page.bringToFront();return{ok,failed,name:String(v.header?.name||v.data?.name||'ChatGPT session').slice(0,80)}}
async function redeem(ticket){const r=await fetch(`${WORKER}/web/host/backup`,{method:'POST',headers:{'content-type':'application/json','x-kyron-browser-host':'project-rev-loopback-v1'},body:JSON.stringify({ticket}),cache:'no-store'});if(!r.ok)throw new Error(r.status===401?'Launch ticket expired.':`Worker handoff failed (${r.status}).`);const ab=await r.arrayBuffer();if(ab.byteLength>70*1024*1024)throw new Error('Session backup is too large.');return Buffer.from(ab)}
function json(res,status,obj){const body=JSON.stringify(obj);res.writeHead(status,{'content-type':'application/json; charset=utf-8','content-length':Buffer.byteLength(body),'cache-control':'no-store','x-content-type-options':'nosniff'});res.end(body)}
function handoffHtml(){return`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Project Rev · ChatGPT</title><style>html,body{height:100%;margin:0;background:#111;color:#eee;font:14px system-ui}main{height:100%;display:grid;place-items:center}.card{width:min(440px,calc(100vw - 40px));padding:24px;border:1px solid #333;border-radius:18px;background:#191919}.muted{color:#999}</style><main><div class="card"><b>Project Rev · ChatGPT</b><p id="s" class="muted">Loading selected session…</p></div></main><script>(async()=>{const s=document.getElementById('s'),ticket=decodeURIComponent(location.hash.slice(1));history.replaceState(null,'','/handoff');if(!ticket){s.textContent='Missing launch ticket.';return}try{const r=await fetch('/launch',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({ticket})}),d=await r.json();if(!r.ok)throw Error(d.error||'Launch failed');s.textContent='ChatGPT opened. This window can be closed.';setTimeout(()=>window.close(),900)}catch(e){s.textContent=e.message||String(e)}})()</script>`}
async function readJson(req,max=16384){const chunks=[];let n=0;for await(const c of req){n+=c.length;if(n>max)throw new Error('Request too large.');chunks.push(c)}try{return JSON.parse(Buffer.concat(chunks).toString('utf8'))}catch{throw new Error('Invalid request.')}}
function local(req){const a=req.socket.remoteAddress||'';return a==='127.0.0.1'||a==='::1'||a==='::ffff:127.0.0.1'}

export function createServer(){return http.createServer(async(req,res)=>{try{if(!local(req)){res.writeHead(403);return res.end()}const u=new URL(req.url||'/',`http://${HOST}:${PORT}`);if(req.method==='GET'&&u.pathname==='/health')return json(res,200,{ok:true,service:'project-rev-browser-host'});if(req.method==='GET'&&u.pathname==='/handoff'){const body=handoffHtml();res.writeHead(200,{'content-type':'text/html; charset=utf-8','content-length':Buffer.byteLength(body),'cache-control':'no-store','x-frame-options':'DENY','content-security-policy':"default-src 'self'; style-src 'unsafe-inline'; script-src 'unsafe-inline'; connect-src 'self'; frame-ancestors 'none'"});return res.end(body)}if(req.method==='POST'&&u.pathname==='/launch'){const b=await readJson(req),ticket=String(b?.ticket||'');if(ticket.length<40||ticket.length>4096||ticket.split('.').length!==3)throw new Error('Invalid launch ticket.');const out=await applySession(await redeem(ticket));return json(res,200,{ok:true,name:out.name,cookies:out.ok,failed:out.failed})}return json(res,404,{error:'Not found.'})}catch(e){return json(res,500,{error:String(e?.message||e).slice(0,180)})}})}

export function start(){const s=createServer();s.listen(PORT,HOST,()=>console.log(`Project Rev browser host listening on http://${HOST}:${PORT}`));return s}
if(process.argv[1]&&import.meta.url===pathToFileURL(path.resolve(process.argv[1])).href)start();
